project:
  type: website

website:
  title: "Lectures"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: "QuantumToolbox.jl"
        menu:
          - text: Introduction
            href: QuantumToolbox.jl/introduction.qmd
          - text: Comparison with other packages
            href: QuantumToolbox.jl/package_comparison.qmd
      - about.qmd
    tools:
      - icon: github
        href:  https://github.com/albertomercurio/Lectures

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-line-numbers: true
    colorlinks: true

execute:
  cache: true
