project:
  type: website

website:
  title: "QuantumToolbox.jl Benchmarks"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: package_comparison.qmd
        text: Comparison with other packages
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



