project:
  type: website

website:
  title: "QuantumToolbox.jl Paper Figures"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: "QuantumToolbox.jl"
        menu:
          - text: Introduction
            href: src/introduction.qmd
          - text: Time Evolution
            href: src/time_evolution.qmd
          - text: Comparison with other packages
            href: src/benchmarks.qmd
      - about.qmd
    tools:
      - icon: github
        href:  https://github.com/albertomercurio/QuantumToolbox.jl-Paper-Figures

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-line-numbers: true
    colorlinks: true
    footnotes-hover: true

execute:
  cache: false
  # freeze: false  # re-render only when source changes
